# Generated by Django 2.1.2 on 2019-03-16 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190316_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.IntegerField()),
                ('GridPosition', models.IntegerField()),
                ('Points', models.FloatField()),
                ('Laps', models.IntegerField()),
                ('AverageSpeed', models.FloatField()),
                ('Stops', models.IntegerField()),
                ('CarNumber', models.IntegerField()),
                ('ArePointsScoring', models.BooleanField()),
                ('ArePointsScoringForTeam', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FinishStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='driverresult',
            name='FinishStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.FinishStatus'),
        ),
        migrations.AddField(
            model_name='driverresult',
            name='VehicleClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.VehicleClass'),
        ),
    ]
