# Generated by Django 2.1.2 on 2019-03-16 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190316_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='Season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raceresult',
            name='Race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Race'),
        ),
        migrations.AddField(
            model_name='driverresult',
            name='RaceResult',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.RaceResult'),
            preserve_default=False,
        ),
    ]
