# Generated by Django 2.1.2 on 2019-03-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190316_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='Number',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driverresult',
            name='Laps',
            field=models.ManyToManyField(null=True, to='web.Lap'),
        ),
    ]
