# Generated by Django 2.1.2 on 2019-03-16 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190316_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamentry',
            name='Season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Season'),
            preserve_default=False,
        ),
    ]
