# Generated by Django 2.1.2 on 2019-03-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_teamentry_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceresult',
            name='DriverResults',
            field=models.ManyToManyField(to='web.DriverResult'),
        ),
    ]
